language: php

php:
  - 7.3

sudo: false

before_script:
 - composer self-update
 - composer install --prefer-source --no-interaction --dev

script: phpunit

matrix:
 allow_failures:
   - php: 7.4
   - php: hhvm
 fast_finish: true

notifications:
  on_success: never
  on_failure: always
  email: lamaaurizkhal@gmail.com
